### PR TITLE
Add: Heavier Benchmark.

### LINKED ISSUE #35: Feature:  Benchmark With heavier payloads
### Describe what you are looking for

Benchmark with heavier payloads, like `1kb` or `3kb` consisting partly from `string` and `binary`.

### Can you contribute to the implementation?

- [X] I can contribute

### Is your feature request specific to a certain interface?

It applies to everything

### Contact Details

_No response_

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ishkhan42**

### CODE REVIEW

**Comment by ishkhan42** [comment]
Benchmarks were conducted on a `c7g.metal` instance using `io_uring`. The setup consisted of one Python server running on a single thread, along with 32 concurrent Python clients.

| Method Name                   | ~ Msg Size (send + recv) | Bandwitdh | Throughput |
| :---------------------- | -----------------: | -----------------: | ----------------------: |
| validate_session  | 190 B |             40 MB/s |            210'000 rps |
| create_user | 1.5 KB |             260 MB/s |            170'000 rps |
| create_user | 5 KB |             725 MB/s |            145'000 rps |

**Comment by ashvardanian** [comment]
How does that new endpoint work, whats inside the message, and how does that compare to analogous FastAPI implementation?

**Comment by ishkhan42** [comment]
The request payload includes random integer `age`, a `name`, a random large string `bio`, and a random binary string `avatar` of the same length. The new endpoint `create_user`, takes in these values as arguments and returns a string that represents a message indicating that the user has been created, including the name, age, length of the avatar image, and bio.

```python
def create_user(age: int, name: str, avatar: bytes, bio: str):
    return f'Created {name} aged {age} with bio {bio} and avatar_size {len(avatar)}'
```

**Comment by ishkhan42** [comment]
The same setup with FastAPI.


| Method Name                   | ~ Msg Size (send + recv) | Bandwitdh | Throughput |
| :---------------------- | -----------------: | -----------------: | ----------------------: |
| validate_session  | 150 B |             0.4 MB/s |            2900 rps |
| create_user | 1.5 KB |             3.6 MB/s |           2400 rps |
| create_user | 5 KB |             11 MB/s |            2350 rps |

**Pull request merged**
