### PR TITLE
Fix typo in README.md: 'ufrom' to 'uform'.

### PR DESCRIPTION
**Pull request by nilq**

### CODE REVIEW

**Comment by ashvardanian** [comment]
Thank you, @nilq 🤗

**Comment by RichardSufliarsky** [comment]
@ashvardanian, sorry to bother you, but typo is still there in `main` branch: https://github.com/unum-cloud/ucall/blob/5c1ab1ff9b9a27cf5ee4a70fb3d4dde7a4ed0c7f/README.md?plain=1#L147

**Comment by ashvardanian** [comment]
Hi @RichardSufliarsky & @nilq! Yes, I need to find a free week to redesign the lib and merge the `main-dev` into `main`. For now, can you please open a PR onto `main` for this typo fix alone? Thanks!

**Comment by RichardSufliarsky** [comment]
done https://github.com/unum-cloud/ucall/pull/112

**Pull request merged**
